config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'reviews#index'
  # root 'users#index'
  resources :reviews do

    member do
      get 'list'
    end

    collection do
      get 'search'
      get 'search-result'
    end
    
  end

  resources :users, only:[:index, :show]

  resources :relationships, only:[:create, :destroy]

  resources :likes, only:[:create,:destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_review, only: [:show, :edit, :update, :destroy] 

  def index
    @rankings = Review.order(likes_count: :desc).limit(4)
    @reviews = Review.order(created_at: :desc).limit(4)
  end

  def new
    @review = Review.new
    4.times{@review.images.build}
  end
  
  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def list
    @reviews = Review.where(user_id: params[:id])
  end

  def show
    @user = User.find(@review.user_id)
  end

  def like_list
    @user = User.find(params[:id])
    @likes = Rike.where(user_id: @user.id)
    @review = Review.where(id: @likes.review_id)
  end

  def edit
    (4 - @review.images.size).times{@review.images.new}
  end

  def update
    if @review.update(review_params)
      if params[:images].present?
        params[:images].each do |i|
          @image = @review.images.create(image: i)
        end
      end
      if params[:delete].present?
        params[:delete].each do |i|
          if i != ""
            @image = Image.find(i)
            @image.delete
          end
        end
      end
      redirect_to review_path(@review)
    end
  end

  def destroy
    if @review.user_id == current_user.id
      @review.destroy
      redirect_to list_reviews_path
    else
      redirect_to root_path
    end
  end
  
  def search
    @q = Review.ransack(params[:q])
    @reviews = @q.result(distinct: true)
  end

  def search_result
    @q = Review.search(search_params)
    @reviews = @q.result(distinct: true)
  end
  
  private
  def review_params
    params.require(:review).permit(
    :name,
    :text,
    :longitude,
    :latitude,
    :address,
    images_attributes:[:image]).merge(user_id: current_user.id)
  end

  def search_params
    params.require(:q).permit!
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/views/reviews/_footer.html.haml
.hooter
  = link_to users_path,class: "hooter__home" do
    %i.fa.fa-home.fa-3x
    .hooter__home__text
      ホーム
  = link_to search_reviews_path,class: "hooter__search" do
    %i.fa.fa-search.fa-3x
    .hooter__search__text
      検索
  .hooter__notification
    %i.fas.fa-user-friends.fa-3x
    .hooter__notification__text
      フォロー
  = link_to new_review_path ,class: "hooter__post" do
    %i.far.fa-clipboard.fa-3x
    .hooter__post__text
      レビュー

app/views/reviews/_header.html.haml
.header
  .header__rogo
    spot-review
  - if user_signed_in?
    = link_to destroy_user_session_path,method: :delete,class: "header__log-out" do
      ログアウト
  - else
    = link_to new_user_registration_path,class: "header__sign-up" do
      新規登録
    = link_to new_user_session_path,class: "header__rogin" do
      ログイン

app/views/reviews/_review.html.haml
.review-post
  .review-post__box
    = form_for @review do |f|
      .review-post__box__logo
        新規レビュー
      .review-post__box__image
        %label.review-post__box__image__btn{for: "review_images_attributes_0_image"}
          画像を選択
          = f.fields_for :images do |i|
            = i.file_field :image, class: "review-post__box__image__btn__form"
        .review-post__box__image__supplement
          最大4枚までアップロードできます。
        .review-post__box__image__box
          -# .review-post__box__image__box__content
          -#   .review-post__box__image__box__content__image
          -#     画像を
          -#     %br 選択してください
          -#   .review-post__box__image__box__content__delete
      .review-post__box__title
        .review-post__box__title__name
          %i.fas.fa-map-pin
          場所の名前
        = f.text_field :name, class: "review-post__box__title__form" 
      .review-post__box__description
        .review-post__box__description__name
          %i.far.fa-comment-alt
          説明
        = f.text_area :text, class: "review-post__box__description__form"
      .review-post__box__place
        .review-post__box__place__name
          %i.fas.fa-location-arrow
          場所
        .review-post__box__place__form
          .review-post__box__place__form__btn
            位置情報を検索
          = f.hidden_field :latitude,class: "review-post__box__place__form__latitude"
          = f.hidden_field :longitude,class: "review-post__box__place__form__longitude"
          = f.hidden_field :address, class: "review-post__box__place__form__address"
          .review-post__box__place__form__address-box
          .review-post__box__place__form__map
      = f.submit "投稿",class: "review-post__box__submit"


      -# .review-post__box__image
      -#   .review-post__box__image__btn
      -#     画像
      -#   .review-post__box__image__supplement
      -#     最大4枚までアップロードできます。
      -#   = f.fields_for :images do |i|
      -#     .review-post__box__image__box
      -#       .review-post__box__image__box__image
      -#         画像を
      -#         %br 選択してください
      -#       = i.label :image, class: "review-post__box__image__box__label",for: "review_images_attributes_0_image" do
      -#         選択
      -#         = i.file_field :image, class: "review-post__box__image__box__label__form"

app/views/reviews/_search-form.html.haml
= render partial: "header"
.search-form
  = search_form_for(@q, url:search_result_reviews_path) do |f|
    = f.label :name, "Keyword", class: "search-form__label"
    = f.search_field :name_or_text_or_address_cont, class: "search-form__field"
    = f.submit "検索", class: "search-form__submit"

app/views/reviews/edit.html.haml
= render partial: "header"
.review-edit
  .review-edit__content
    = form_for @review do |f|
      .review-edit__content__name
        = f.text_field :name, class: "review-edit__content__name__form" 
      .review-edit__content__time
        = @review.created_at.strftime("%Y-%m-%d %H:%M")
      .review-post__box__image
        %label.review-post__box__image__btn{for: "review_images_attributes_0_image"}
          画像を選択
          = f.fields_for :images do |i|
            = i.file_field :image,name: "images[]", class: "review-post__box__image__btn__form"
        .review-post__box__image__supplement
          最大4枚までアップロードできます。
        .review-post__box__image__box
          - @review.images.each do |image|
            - if image.image.present?
              .review-post__box__image__box__content
                = image_tag image.image.url, class: "review-post__box__image__box__content__image"
                %a.review-post__box__image__box__content__delete{href: "" , "data-id": image.id}
                  削除
      .review-edit__content__text
        = f.text_area :text, class: "review-edit__content__text__form"
      .review-edit__content__address
        = @review.address
      .review-edit__content__map
        %a.show-edit__content__map__btn{href: "",data: {lat: @review.latitude,long: @review.longitude}}地図を表示
        .show-edit__content__map__box
      .review-edit__content__btn
        = f.submit "変更する",class: "review-edit__content__btn__submit"

app/views/reviews/index.html.haml
= render partial: "header"
.main
  .main__content1
    .main__content1__rogo
      Ranking
    .main__content1__list
      - @rankings.each do |ranking|
        = link_to review_path(ranking),class: "main__content1__list__one" do
          .main__content1__list__one__name
            = ranking.name
          .main__content1__list__one__like
            %i.fas.fa-heart{id: "no-click-like"}
            = ranking.likes.count
          .main__content1__list__one__image
            = image_tag ranking.images.first&.image.url,class: "main__content1__list__one__image__display"
          .main__content1__list__one__address
            = ranking.address
  .main__content2
    .main__content2__rogo
      新着レビュー
    .main__content2__list
      - @reviews.each do |review|
        = link_to review_path(review),class: "main__content2__list__one" do
          .main__content2__list__one__name
            = review.name
          .main__content2__list__one__like
            %i.fas.fa-heart{id: "no-click-like"}
            = review.likes.count
          .main__content2__list__one__image
            = image_tag review.images.first&.image.url,class: "main__content2__list__one__image__display"
          .main__content2__list__one__address
            = review.address
= render partial: "footer"

app/views/reviews/list.html.haml
= render partial: "header"
.review-list
  .review-list__field
    .review-list__field__logo
      レビュー投稿一覧
    .review-list__field__list
      - @reviews.each do |review|
        = link_to review_path(review),class: "review-list__field__list__content" do
          .review-list__field__list__content__name
            = review.name
          .review-list__field__list__content__like
            %i.fas.fa-heart{id: "no-click-like"}
            = review.likes.count
          .review-list__field__list__content__image
            = image_tag review.images.first&.image.url,class: "review-list__field__list__content__image__display"
          .review-list__field__list__content__address
            = review.address
= render partial: "footer"

app/views/reviews/new.html.haml
= render partial: "header"
= render partial: "review"

app/views/reviews/search.html.haml
= render partial: "search-form"

app/views/reviews/search_result.html.haml
= render partial: "search-form"
.search-sort
  = sort_link(@q, :name, "タイトル順", class: "search-sort__content")
  = sort_link(@q, :text, "text", class: "search-sort__content")
  = sort_link(@q, :address, "address", class: "search-sort__content")
  = sort_link(@q, :likes_count, "いいね順", class: "search-sort__content")
.search-result
  - @reviews.each do |review|
    = link_to review_path(review), class: "search-result__content" do
      .search-result__content__name
        .search-result__content__name__box
          = review.name
      .search-result__content__like
        %i.fas.fa-heart{id: "no-click-like"}
        = review.likes_count
      .search-result__content__image
        = image_tag (review.images.first&.image.url),class:"search-result__content__image__box"
      .search-result__content__text
        .search-result__content__text__logo
          text
        .search-result__content__text__box
          = review.text
      .search-result__content__address
        .search-result__content__address__logo
          address
        .search-result__content__address__box
          = review.address

app/views/reviews/show.html.haml
= render partial: "header"
.review-show
  .review-show__content
    =link_to user_path(@user.id), class: "review-show__content__user" do
      .review-show__content__user__image
        - if @user.image.present?
        - else
          = image_tag 'profile.jpeg', class: "review-show__content__user__image__noimage"
      .review-show__content__user__name
        = @user.nickname
    .review-show__content__name
      .review-show__content__name__explanation
        title
      .review-show__content__name__title
        = @review.name
    .review-show__content__like
      - if @review.user_id == current_user.id
        .review-show__content__like__no-click
          %i.fas.fa-heart{id: "no-click-like"}
          = @review.likes.count
      - else
        - if current_user.likes.find_by(review_id: @review.id)
          %a.review-show__content__like__delete{href: "" , "data-id": @review.id}
            %i.fas.fa-heart{id: "click-like"}
            = @review.likes.count
        - else
          %a.review-show__content__like__create{href: "" , "data-id": @review.id}
            %i.far.fa-heart{id: "click-like"}
            = @review.likes.count
    .review-show__content__time
      = @review.created_at.strftime("%Y-%m-%d %H:%M")
    .review-show__content__image
      - @review.images.each do |image|
        .review-show__content__image__box
          = image_tag image.image.url, class: "review-show__content__image__box__display"
    .review-show__content__text
      .review-show__content__text__explanation
        text
      .review-show__content__text__text
        = @review.text
    .review-show__content__address
      .review-show__content__address__explanation
        address
      .review-show__content__address__address
        = @review.address
    .review-show__content__map
      %a.show-edit__content__map__btn{href: "",data: {lat: @review.latitude,long: @review.longitude}}地図を表示
      .show-edit__content__map__box
    .review-show__content__btn
      - if @review.user_id == current_user.id
        = link_to list_review_path(@user),class: "review-show__content__btn__return" do
          一覧へ戻る
        = link_to edit_review_path(@review),class: "review-show__content__btn__edit" do
          編集をする
        = link_to review_path(@review),method: :delete,class: "review-show__content__btn__edit" do
          削除する
      - else
        -# = link_to
        -# 戻るリンク
        -# ユーザーのプロフィールページへ飛ぶリンク